############################################
##
##  capacity storage: 2Gi
##  /storage/data-postgresql-pv-0 must be created before
##
############################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-0
spec:
  storageClassName: postgresql-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/storage/data-postgresql-pv-0"
